// Generated by gencpp from file project_1/TwoInts.msg
// DO NOT EDIT!


#ifndef PROJECT_1_MESSAGE_TWOINTS_H
#define PROJECT_1_MESSAGE_TWOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project_1
{
template <class ContainerAllocator>
struct TwoInts_
{
  typedef TwoInts_<ContainerAllocator> Type;

  TwoInts_()
    : A(0)
    , B(0)  {
    }
  TwoInts_(const ContainerAllocator& _alloc)
    : A(0)
    , B(0)  {
  (void)_alloc;
    }



   typedef int64_t _A_type;
  _A_type A;

   typedef int64_t _B_type;
  _B_type B;





  typedef boost::shared_ptr< ::project_1::TwoInts_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project_1::TwoInts_<ContainerAllocator> const> ConstPtr;

}; // struct TwoInts_

typedef ::project_1::TwoInts_<std::allocator<void> > TwoInts;

typedef boost::shared_ptr< ::project_1::TwoInts > TwoIntsPtr;
typedef boost::shared_ptr< ::project_1::TwoInts const> TwoIntsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project_1::TwoInts_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project_1::TwoInts_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace project_1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'project_1': ['/home/andrestoga/Dropbox/ros/robotics-course-columbia/src/project_1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::project_1::TwoInts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_1::TwoInts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_1::TwoInts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_1::TwoInts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_1::TwoInts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_1::TwoInts_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project_1::TwoInts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02f05bb5bde9ff0aeeed7cca0d2e13fc";
  }

  static const char* value(const ::project_1::TwoInts_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02f05bb5bde9ff0aULL;
  static const uint64_t static_value2 = 0xeeed7cca0d2e13fcULL;
};

template<class ContainerAllocator>
struct DataType< ::project_1::TwoInts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_1/TwoInts";
  }

  static const char* value(const ::project_1::TwoInts_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project_1::TwoInts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 A\n"
"int64 B\n"
;
  }

  static const char* value(const ::project_1::TwoInts_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project_1::TwoInts_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
      stream.next(m.B);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TwoInts_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project_1::TwoInts_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project_1::TwoInts_<ContainerAllocator>& v)
  {
    s << indent << "A: ";
    Printer<int64_t>::stream(s, indent + "  ", v.A);
    s << indent << "B: ";
    Printer<int64_t>::stream(s, indent + "  ", v.B);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_1_MESSAGE_TWOINTS_H
